channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bcftools=1.22
- bioconda::bwa=0.7.19
- bioconda::fastp=1.0.1
- bioconda::freebayes=1.3.10
- bioconda::hostile=2.0.2
- bioconda::pysam=0.23.3
- bioconda::samtools=1.22.1
- bioconda::seqtk=1.5
- bioconda::squirrel=1.2.2
- bioconda::tabix=1.11
- conda-forge::biopython=1.85
- conda-forge::bzip2=1.0.8
- conda-forge::clint=0.5.1
- conda-forge::gzip=1.14
- conda-forge::pandas=2.3.2
- conda-forge::requests=2.32.5
